version: '3'
services:
  dashboard:
    container_name: bgp3-board
    ports:
     - "192.168.1.101:80:80"
     - "192.168.1.101:443:443"
    image: "bgp_dash"
    privileged: true
    restart: unless-stopped
